### PR TITLE
[🐞Fix And New Command] Case sensitive ENV_VAR and missing DBL_TOKEN

### PR DESCRIPTION
**Pull request by felixfong227**
## 🐞Fix:
1) Due to the facts that I am using [SecretHub](https://secrethub.io/) and not using `dotenv` library, the `TOKEN` environment variable is a bit different for me, so what I did is I conditionally imports the bot token based on ENV_VAR existence

2) If the host machine is missing a key environment variable `DBL_TOKEN`, the bot will crash, so what I did is conditionally loading the related modules into the runtime

## New Commands

`;;fox-info`
What this command do is very similar to the origin `;;fox` command does, but the key difference is it will fetch the image source from a site call [Fox-Info.net](http://fox-info.net) and with a bit of caching with Redis DB

## Changes

1) Due to the `;;fox-info` uses RedisDB, so I thought it's a good idea to wrap things up with Docker, so I put a few Docker related config files into the source code namely `Dockerfile` and `docker-compose.yml`

2) Adding a `RGB` output to the `;;colour` command
image

### CODE REVIEW

**Comment by VenkSociety** [comment]
Hello Felix, unfortunately after testing these commits the bot no longer starts regularly. Have you tried running the bot through the standard node prompt? 

**Error 1:**
`Error: An invalid token was provided.`

**Error 2:**
 ```
{ Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'redis',
  host: 'redis',
  port: 6379 }
Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
```

I also don't see much use for the new `;;fox-info` command seeing as `;;fox` does the same thing but more easily, could you elaborate on how the new edition is better?

Everything else seems fine to me and I'd be happy to add these changes but you should probably find a way to fix those errors stated above before I can do so. Cheers.

**Comment by felixfong227** [comment]
## Fox command related issues:

About the `;;fox-info` command, the site [fox-info.net](http://fox-info.net) will basically upload at least one photo per day, that everyone picture is taken from a place called "Zao Fox Village" located in 🇯🇵 . So a fox lover like me and my girlfriend and many other bot users could have a most updated version of those pictures.

On second thought, to avoid any confusion between that two commands, do you think it's a good idea to actually put `fox-info` as a command argument instead? For example `;;fox info` will using the "fox-info.js" and the regular `;;fox` will use the "fox.js" module?

## Redis issues

The reason the bot is throwing Redis connection is that my version of the bot is designed to run under the Docker (docker-compose) environment thus it expects there is a hostname called "redis" with an open port "6379"


---

 And as for the environment variable issue, I am taking a look and try to figure out what when wrong right now.

Thank you

**Comment by felixfong227** [comment]
👋 @VenkSociety I just pushed two more commits that will solve the token ENV_VAR issues 😄

**Comment by VenkSociety** [comment]
@felixfong227 those didn't appear to fix the errors. Once again have you tried running through a regular NPM environment or do the errors not show for you? A full log of what I got when starting the bot can be found via [this pastebin link](https://pastebin.com/X5rdVAx2).

As for the `;;fox-info` suggestion, I'm fine with either a command argument or even simply just using the new revision.

**Comment by felixfong227** [comment]
So sorry for the awful confusion, I manage to add a new `usingRedis` flag thus allowing the `;;fox-info` to work with and without a Redis connection.

One more thing I want to confirm, are you suggesting I can drop the `;;fox` module and replace with the `;;fox-info` module?

**Comment by VenkSociety** [comment]
Does `;;fox-info` absolutely require redis? Nothing you've done so far has managed to fix it and yes, if you get ;;fox-info to work without redis, we can replace the old ;;fox module.

**Comment by felixfong227** [comment]
🤔 with the last couples of commit I do believe I managed to make the fox-info work completely fine without Redis

**Comment by VenkSociety** [comment]
Just ran it then:

```
[Redis] Redis connection fail, going to discontinue using Redis as a cache service for ;;fox-info
[Redis] Quitting Redis connection
Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (C:\Users\dzdez\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:286:20)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.onClose (C:\Users\dzdez\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\dzdez\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (C:\Users\dzdez\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\dzdez\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:606:12)
Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (C:\Users\dzdez\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:286:20)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.onClose (C:\Users\dzdez\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\dzdez\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (C:\Users\dzdez\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\dzdez\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:606:12)
```

**Comment by felixfong227** [comment]
image

That's odd, because I just try ran the bot via Glitch.com(in the most purest Node environment I could possibly think of) and it work just fine 🤔

**Comment by felixfong227** [comment]
According to our conversation via Discord, this should do it(I hope lul

**Comment by VenkSociety** [comment]
Mission complete.

**Pull request merged**
